[package]
name = "vendace"
version = "0.1.0"
edition = "2021"
authors = ["Antoni Przybylik <antoni.przybylik@wp.pl>"]
license = "GPL-2.0"

[dependencies]
rayon = "1.7.0"
anyhow = "1.0.72"
lazy_static = "1.4.0"
